# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ownfarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Client')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Farm')),
            ],
        ),
    ]
