# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropproductiondisease',
            options={'managed': False, 'verbose_name': 'Maladie', 'verbose_name_plural': 'Maladies sureill\xe9es'},
        ),
    ]
