# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0002_ownfarm'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropProduction',
            fields=[
                ('crop_production_id', models.AutoField(primary_key=True, serialize=False)),
                ('crop', models.CharField(blank=True, max_length=6, null=True)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('yield_field', models.FloatField(blank=True, db_column='yield', null=True)),
                ('comments', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'crop_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('disease_id', models.AutoField(primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'disease',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.AutoField(primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=50)),
                ('latitude_n', models.FloatField()),
                ('longitude_n', models.FloatField()),
                ('latitude_s', models.FloatField()),
                ('longitude_s', models.FloatField()),
                ('soil_type', models.CharField(blank=True, max_length=10, null=True)),
                ('comments', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'plot',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('sensor_id', models.AutoField(primary_key=True, serialize=False)),
                ('sensor_type', models.CharField(max_length=20)),
                ('sensor_unit', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'sensor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CropProductionDisease',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SensorPlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, null=True)),
                ('plot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Plot')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Sensor')),
            ],
        ),
        migrations.CreateModel(
            name='CropProductionSensor',
            fields=[
                ('crop_production', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='APDM.CropProduction')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Sensor')),
            ],
        ),
        migrations.AddField(
            model_name='cropproductiondisease',
            name='crop_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.CropProduction'),
        ),
        migrations.AddField(
            model_name='cropproductiondisease',
            name='disease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.Disease'),
        ),
    ]
