# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 19:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0002_auto_20170503_2003'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cropproductiondisease',
            table='apdm_cropproductiondisease',
        ),
    ]
