# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0003_auto_20170503_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cropproductiondisease',
            options={'verbose_name': 'Maladie', 'verbose_name_plural': 'Maladies sureill\xe9es'},
        ),
    ]
