# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0003_auto_20170313_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_date', models.DateField()),
                ('feedback_treated', models.IntegerField(blank=True, null=True)),
                ('feedback_date', models.DateField(blank=True, null=True)),
                ('alert_confirmed', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alert',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anomaly',
            fields=[
                ('anomaly_id', models.AutoField(primary_key=True, serialize=False)),
                ('occurence_date', models.DateField()),
                ('reporting_date', models.DateField()),
                ('treated', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'anomaly',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FhbPredictions',
            fields=[
                ('prediction_id', models.AutoField(primary_key=True, serialize=False)),
                ('predcition_date', models.DateTimeField()),
                ('crop_production', models.IntegerField()),
                ('temp_duration', models.FloatField()),
                ('humidity_avg', models.FloatField()),
                ('rainfall_duration', models.FloatField()),
                ('class_field', models.CharField(db_column='class', max_length=10)),
                ('risk_rate', models.FloatField()),
            ],
            options={
                'db_table': 'fhb_predictions',
                'managed': False,
            },
        ),
    ]
