# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 17:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0004_auto_20170503_2332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alert',
            options={'verbose_name': 'Alerte', 'verbose_name_plural': 'Alertes'},
        ),
        migrations.AlterModelOptions(
            name='alertclient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='anomaly',
            options={'verbose_name': 'Anomalie', 'verbose_name_plural': 'Anomalies'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'Ville', 'verbose_name_plural': 'Villes'},
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Utilisateur', 'verbose_name_plural': 'Utilisateurs'},
        ),
        migrations.AlterModelOptions(
            name='crop',
            options={'verbose_name': 'Type de culture', 'verbose_name_plural': 'Types de cultures'},
        ),
        migrations.AlterModelOptions(
            name='cropclient',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cropproduction',
            options={'verbose_name': 'Culture', 'verbose_name_plural': 'Cultures'},
        ),
        migrations.AlterModelOptions(
            name='disease',
            options={'verbose_name': 'Maladie', 'verbose_name_plural': 'Maladies'},
        ),
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'Ferme', 'verbose_name_plural': 'Fermes'},
        ),
        migrations.AlterModelOptions(
            name='plot',
            options={'verbose_name': 'Parcelle', 'verbose_name_plural': 'Parcelles'},
        ),
        migrations.AlterModelOptions(
            name='sensor',
            options={'verbose_name': 'Capteur', 'verbose_name_plural': 'Capteurs'},
        ),
        migrations.AlterModelTable(
            name='cropproductiondisease',
            table=None,
        ),
    ]
