# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0004_alert_anomaly_djangomigrations_fhbpredictions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorplot',
            old_name='date_fin',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='sensorplot',
            old_name='date_debut',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='cropproductionsensor',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cropproductionsensor',
            name='crop_production',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APDM.CropProduction'),
        ),
    ]
