# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0005_auto_20170316_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={},
        ),
    ]
