# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0009_auto_20170316_1740'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='apdm_client',
        ),
    ]
