# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APDM', '0010_auto_20170316_1741'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelTable(
            name='client',
            table=None,
        ),
    ]
